<b> NUMPY   |    PANDAS    |     MATPLOTLIB </b>

In [1]:
import numpy as np
np.__version__

'1.20.3'

In [2]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
food_arr = ['rice', 'beans', 'yam', 'potato', 'garri']
np.array(food_arr)

array(['rice', 'beans', 'yam', 'potato', 'garri'], dtype='<U6')

<b>ndarray - n dimensional array</b>

In [4]:
arr = [[1, 2, 3], [4, 5, 6]]
np.array(arr)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
np.array(arr).ndim

3

In [6]:
arr = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
np.array(arr)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
for i in arr:
    if isinstance(i, list):
        for j in i:
            if isinstance(j, list):
                for k in j:
                    print(k)
            else:
                print(j)
    else:        
        print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [8]:
for i in np.nditer(arr):
    print(i)

(array(1), array(7))
(array(2), array(8))
(array(3), array(9))
(array(4), array(10))
(array(5), array(11))
(array(6), array(12))


In [9]:
for i in np.nditer(np.array(arr)):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [10]:
for i in np.nditer(np.array(arr)[:, ::2]):
    print(i)

1
2
3
7
8
9


<b>GET INDEX OF ARRAY ELEMENTS</b>

In [11]:
for index, x in np.ndenumerate(arr):
    print(index, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [12]:
for i in np.nditer(np.array(arr), flags = ['buffered'], op_dtypes = ['float']):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0


In [13]:
for i in np.nditer(np.array(arr), flags = ['buffered'], op_dtypes = ['S']):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


In [14]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array((6, 7, 8))
newarr = np.concatenate((arr1, arr2))
newarr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array((6, 7, 8), dtype = 'S')
np.concatenate((arr1, arr2))

array([b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8'], dtype='|S11')

In [16]:
np.array_split(newarr, 3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

6/21/23 - CLASS

In [17]:
arr_1 = np.array([[1, 2], [3, 4]])
arr_2 = np.array([[5, 6], [7, 8]])
np.stack((arr_1, arr_2), axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [18]:
np.hstack((arr_1, arr_2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [19]:
np.vstack((arr_1, arr_2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
np.dstack((arr_1, arr_2))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [21]:
arr = np.array([['a', 'b', 'c'], ['d', 'e', 'a'], ['g', 'h', 'a'], ['j', 'k', 'l'], ['m', 't', 'o'], ['p', 'q', 'r']])
x = np.where(arr == 'a')
print("SEARCHING ARRAY")
print(x)

SEARCHING ARRAY
(array([0, 1, 2], dtype=int64), array([0, 2, 2], dtype=int64))


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [23]:
arr = np.array([6, 8, 9, 7])
np.searchsorted(arr, 7)

1

In [24]:
np.searchsorted(arr, 7, side='right')

1

In [26]:
arr = np.array([1, 3, 5, 7])
np.searchsorted(arr, [2, 4, 8])

array([1, 2, 4], dtype=int64)